### ISSUE TITLE
App crashes whenever lyrics load.

### ISSUE THREAD

**Issue by Mweeg** [SpotCompiled/SpotveeC#3]
The latest version crashes whenever the lyrics page is loaded. This is done automatically by the app and you can't NOT load it if you want to skip songs or view the queue.

**Comment by yodaluca23** [comment]
I am unable to reproduce this. Can you give me all the details about your environment?


On May 5, 2024, at 3:06 PM, Mweeg ***@***.***> wrote:

﻿

The latest version crashes whenever the lyrics page is loaded. This is done automatically by the app and you can't NOT load it if you want to skip songs or view the queue.

**Comment by Mweeg** [comment]
ios: 17.4 beta 1. Signed with developer cert.

**Comment by Mweeg** [comment]
fuck misclick

**Comment by shawnamey** [comment]
Same issue just installed/sideloaded through Sidestore.

When the song is full display once lyrics loads the app crashes.

Can only bypass partially when the album cover is not on full display and only played through mini display.

**Comment by shawnamey** [comment]
Note* downgraded to the previous release candidate and that doesn't crash lyrics even if no lyrics are displayed or nulled.

**Comment by yodaluca23** [comment]
This should be fixed in the next release, I just don't have time to work on it right now, with finals and AP exams, should be able to get it out ether Friday or the weekend.

**Comment by 3xynos7** [comment]
> This should be fixed in the next release, I just don't have time to work on it right now, with finals and AP exams, should be able to get it out ether Friday or the weekend.

Ok Bruh.

**Comment by yodaluca23** [comment]
Can you test if this is still present in the latest release, 2.0.1?

**Comment by 3xynos7** [comment]
> Can you test if this is still present in the latest release, 2.0.1?

Still present in this version 2.0.1.![image](https://github.com/SpotCompiled/SpotveeC/assets/168754311/42f68bb7-4ded-4962-98eb-1dc0854427dc)

**Comment by yodaluca23** [comment]
> Still present in this version 2.0.1.![image](https://github.com/SpotCompiled/SpotveeC/assets/168754311/42f68bb7-4ded-4962-98eb-1dc0854427dc)

This is an intensional feature, prior version simply didn't notify you. Spotify just refreshes the offline.bnk from time to time, this file is what spoofs the premium. When you relaunch the app, EeveeSpotify re-patches the file, to enable premium. There is no way to avoid Spotify refreshing it.

What I was referring to is the crash, when viewing the lyrics card, which is loaded automatically anytime you in the full media view.

**Comment by 3xynos7** [comment]
Reinstalled! Working completely fine now, some lyrics are completely messed up, shows lyrics of different song. I think it's the problem with the lyrics server/api to show different lyrics and time sync. Other than this working perfectly fine now.

**Comment by shawnamey** [comment]
No longer crashes in full media view, regardless of Lyrics loading with data or nulled.

The only issue is spotvee needing to restart for cache but I don't believe that can be resolved and just an issue to spoof premium.

**Comment by 3xynos7** [comment]
@yodaluca23 This most recent version 2.1.0 is operating flawlessly with the new lyrics source option. Should we anticipate that a next version would, perhaps, support offline saving as well? Though I am aware that it is a server-side feature, are there not other options for integration? By the way, I appreciate that you integrated Lyric Source, especially "Musixmatch."
